### ISSUE TITLE
API 'variant.getJavaCompile()' is obsolete

### ISSUE THREAD

**Issue by pani7** [Gaspard-Bruno/react-native-static-safe-area-insets#7]
Hi, after linking library to android and after syncing project i get this error in build.gradle of your package:

> API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

As i browsed for this error it might  have something to do with 'com.android.tools.build:gradle:2.2.3' dependency in build.gradle of your package and current version is 3.4.1 . When i change manually to newest it does not compile because it can not find it. 
How to solve this error?

**Comment by CarlosUvaSilva** [comment]
hello @pani7, a new version has been released [v1.3.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v1.3.0) and your issue should be fixed

Thank you

**Comment by pani7** [comment]
Thank you for prompt response but unfortunately error remains the same:

API 'variant.getJavaCompile()' is obsolete and has been replaced with
> 'variant.getJavaCompileProvider()'.
> It will be removed at the end of 2019.
> For more information, see
> https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getJavaCompile(), use
> -Pandroid.debug.obsoleteApi=true on the command line to display a stack
> trace.
>

I guess it might have something to do with this code in build.gradle of
your package:

> android.libraryVariants.all { variant ->
>     def name = variant.name.capitalize()
>     task "jar${name}"(type: Jar, dependsOn: variant.javaCompile) {
>         from variant.javaCompile.destinationDir
>     }
> }
>
> Also after running jest tests they fail with error message:

TypeError: Cannot read property 'safeAreaInsetsTop' of undefined

I am importing it normal:
import StaticSafeAreaInsets from 'react-native-static-safe-area-insets';
Then using it in code:

> const insets = StaticSafeAreaInsets.safeAreaInsetsTop +
> StaticSafeAreaInsets.safeAreaInsetsBottom;


And it works as it is supposed to, but i get this error on tests. I really
like your solution because it does not return promise.
Sorry to bother you but it would be very helpful if you could change that
part in build gradle that is causing problems.

Thank you and have a nice day



čet, 30. svi 2019. u 15:21 CarlosUvaSilva <notifications@github.com>
napisao je:

**Comment by CarlosUvaSilva** [comment]
Could you please try the code from this branch: [javacompile](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/tree/javacompile) and check if it solves your test

we can't easily reproduce your bug

**Comment by pani7** [comment]
It seems to be working now. Thank you for your help. I gave you a star 😉.

pet, 31. svi 2019. u 15:54 CarlosUvaSilva <notifications@github.com>
napisao je:

**Comment by CarlosUvaSilva** [comment]
[javacompile](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/tree/javacompile) has been merged to master and a new version has been published [1.3.3](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v1.3.3)

Thank you for the ⭐️
